book(the_belgariad, david_eddings).
book(the_mallorean, david_eddings).
book(harry_potter_and_the_prisoner_of_azkaban, j_k_rowling).
book(harry_potter_and_the_philosophers_stone, j_k_rowling).
book(across_the_nightingale_floor, liam_hearn).
book(dragoncharm, graham_edwards).
book(all_the_weyrs_of_pern, anne_mccaffrey).
book(dragonflight, anne_mccaffrey).
book(the_white_dragon, anne_mccaffrey).
book(rhapsody, elizabeth_haydon).
book(prophecy, elizabeth_haydon).
book(destiny, elizabeth_haydon).
book(mort, terry_pratchett).
